### ISSUE TITLE
Wrong description in README

### ISSUE THREAD

**Issue by surjendu104** [vixy-mixy/User-Registration-Demo#17]
There is wrong description in README. It is a demo user registration app. but in readme it written about course adding.
Assign it to me to resolve it.

**Comment by vixy-mixy** [comment]
Yeah I have seen it. assigning you

**Comment by surjendu104** [comment]
Hey @vixy-mixy  I have made a PR for this issue. Do check it out and let me know if any changes needed.

**Comment by vixy-mixy** [comment]
It seems fine to me. Thanks @surjendu104 for your contribution.
