### ISSUE TITLE
Edit application.properties for database connection and configuration

### ISSUE THREAD

**Issue by vixy-mixy** [vixy-mixy/User-Registration-Demo#2]
I prefer MySQL db. Edit the application.properties to connect to mysql database and configure hibernate for JPA

**Comment by mslowiak** [comment]
Hi @vixy-mixy :) 
Can I help you with that?

**Comment by techrajdeep** [comment]
Hi @vixy-mixy  Please assign me the issue ..if it is still open

**Comment by vixy-mixy** [comment]
Hi everyone!!
This issue is resolved But you can suggest your ideas about this project's future. Issues and PRs are welcomed
